config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :jobs
  root 'events#home'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :jobs, :dependent => :destroy

  # You can chain these
  # lookup scopes here: http://api.rubyonrails.org/classes/ActiveRecord/Scoping/Named/ClassMethods.html
  scope :not_expired, -> { where('event_time_start > ?', Time.now)}
  scope :overbooked, -> { where('slots < jobs_count') }
  scope :full, -> { where('slots = jobs_count') }
  scope :this_month, -> { where("DATE_PART('month', event_time_start) = ?", Time.now.month)}

  # Event.already_applied(User.first)
  scope :already_applied, -> (user) { joins(:jobs).where('user_id = ?', user.id) }


  # Methods for individual events
  def expired?
    event_time_start > Time.now
  end

  def overbooked?
    slots < jobs_count
  end

  def full?
    slots == jobs_count
  end

  def already_applied?(user)
    jobs.pluck(:user_id).include? user.id
  end

  def length_in_hours
    ((event_time_finish - event_time_start) / 3600).round
  end

  def self.hours_this_month
    this_month.to_a.sum(&:length_in_hours)
  end

  def self.hours_this_month_for_user(user, event_type)
    joins(:jobs).where('events.event_type = ?', event_type).where('jobs.user_id = ?', user.id).to_a.sum(&:length_in_hours)
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
  belongs_to :event, counter_cache: true
  # For event counter cache of jobs_count:
  # counter cache, stores number of jobs on the event.
  # otherwise I have to do SELECT count(*) FROM jobs where event_id = 1 for each event.
  # http://yerb.net/blog/2014/03/13/three-easy-steps-to-using-counter-caches-in-rails/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :jobs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_up) << :user_level
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, except: [:home]
    before_action :set_event, only: [:show, :edit, :update, :destroy]


  def index
    @events = Event.all
  end

  def new
    @event = Event.new
    @user = current_user.email
  end

  def show
  end

  def edit
    @user = current_user.email
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
    end
  end

private

    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:jobs_count, :event, :event_type, :location, :slots, :created_by, :event_time_start, :event_time_finish)
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :authenticate_user!
    # before_action :set_job, only: [:show, :edit, :update, :destroy]


  def index
    @jobs = Job.where(user_id: current_user.id)
    @events = Event.all
    @team_hours = Event.hours_this_month_for_user(current_user, 'Team Event')
    @org_hours = Event.hours_this_month_for_user(current_user, 'Organization Event')
    @total_hours = @team_hours + @org_hours
  end

  def new
    @job = Job.new
    @events = Event.all
    @count = Event.count
    @date = Time.now
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
  end

  def create
    @job = Job.new(job_params)
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @jobs = Job.find(params[:id])
    @jobs.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Job was successfully destroyed.' }
    end
  end

private

    def set_job
      @job = Job.find(params[:user_id])
    end

    def job_params
      params.require(:job).permit(:user_id, :event_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>

    <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event %><br>
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :event_type %><br>
    <%= f.select(:event_type, ['Team Event', 'Organization Event'], {include_blank: "Select something"}) %>
  </div>
  <div class="field">
  <%= f.label "Start Time and Date" %><br>
  <%= f.datetime_select :event_time_start, ampm: true %>
  </div>
  <div class="field">
  <%= f.label "Finish Time and Date" %><br>
  <%= f.datetime_select :event_time_finish, default: 3.days.from_now, ampm: true %>
  </div>
  <div class="field">
  <%= f.label :location %><br>
  <%= f.text_field :location %>
  </div>
  <div class="field">
  <%= f.label :slots %><br>
  <%= f.text_field :slots %>
  </div>
  <div class="field">
  <%= f.hidden_field :created_by, :value => @user %>
  <%= f.hidden_field :jobs_count, :value => 0 %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event, class: 'btn btn-default' %>
<%= link_to 'Back', events_path, class: 'btn btn-default' %>

app/views/events/home.html.erb
HOME PAGE
<%= link_to 'Volunteer slots', jobs_path, class: 'btn btn-default' %>
<%= link_to 'Create a new event', events_path, class: 'btn btn-default'%>

app/views/events/index.html.erb
<table class="index_table">
<tr>
  <th> #id </th>
  <th> Event Name </th>
  <th> Event Type </th>
  <th></th>
</tr>
<% @events.each do |event| %>
  <tr>
    <td><%= event.id %></td>
    <td><%= event.event %></td>
    <td><%= event.event_type %></td>
    <td><%= link_to 'Show', event, class: 'btn btn-default' %>
    <%= link_to 'Edit', edit_event_path(event), class: 'btn btn-default' %>
    <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning' %></td>
  </tr>
<% end %>
</table>
<% if current_user.user_level == 'Event Organizer' or current_user.user_level == 'Managment' %>
<%= link_to 'New event', new_event_path, class: 'btn btn-default' %>
<% end %>

<%= link_to 'Back', root_path, class: 'btn btn-default' %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path, class: 'btn btn-default' %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @event.id %><br>
  <%= @event.event %><br>
  <%= @event.event_time_start%> to <br>
  <%= @event.event_time_finish%> <br>
  <%= @event.event_type %><br>
  <%= @event.location %><br>
  <%= @event.created_by %><br>
</p>

<%= link_to 'Edit', edit_event_path(@event), class: 'btn btn-default' %>
<%= link_to 'Back', events_path, class: 'btn btn-default' %>

app/views/jobs/index.html.erb
Your Jobs page
<br>
Total Hours:  <%= @total_hours %>
Team Hours: <%= @team_hours %>
Organization Hours: <%= @org_hours %>
<% if @org_hours >= 5 and @total_hours > 20 %>
  <button type="button" class="btn btn-success">Hours Meet</button>
<% else %>
  <button type="button" class="btn btn-danger">Hours Not Meet</button>
<% end %>
<br>
<table>
  <tr>
  <th> #id </th>
  <th> Event Name </th>
  <th> Event Type </th>
  <th> Event Date</th>
  <th> Hours </th>
  <th> Verified </th>
  <th></th>
  </tr>
  <tr>
<% @jobs.each do |job| %>
  <td><%= job.id %></td>
  <td><%= job.event.event %></td>
  <td><%= job.event.event_type %></td>
  <td><%= job.event.event_time_start %> to
  <%= job.event.event_time_finish %></td>
  <td><%= ((job.event.event_time_finish.to_i - job.event.event_time_start.to_i) / 3600) %></td>
  <td>
    <% if job.verified == nil %>
      <button type="button" class="btn btn-default">Scheduled</button>
    <% elsif job.verified == true %>
      <button type="button" class="btn btn-success">Verfied</button>
    <% elsif job.verified == false %>
      <button type="button" class="btn btn-danger">Not Verified</button>
    <% end %>
  </td>
  <td><%= link_to 'Show', job, class: 'btn btn-default' %>
  <%= link_to 'Decline', job, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning' %></td>
  </tr>
<% end %>
</table>
<% if @jobs == [] %>
"Help the Team... sad face... :-(
<% end %>
<%= link_to 'Back', root_path, class: 'btn btn-default' %>

<%= link_to 'Apply for slot', new_job_path , class: 'btn btn-default'%>

app/views/jobs/new.html.erb
Avalable jobs

<%= @date %>
<br>
<table>
<tr>
  <th> Event Name </th>
  <th> Event Date </th>
  <th> Event Type </th>
  <th> Slots</th>
  <th> Status </th>
  <th></th>
</tr>
<% @events.each do |event| %>
<tr>
  <% if current_user.user_level == 'Managment' %>
    <td> <%= event.event %></td>
    <td> date: <%= event.event_time_start %></td>
    <td>  <%= event.event_type %> </td>
    <td>Slots: <%= event.slots %> / <%= event.jobs_count %></td>
    <td>
            <% if event.expired? == false %>
              <button type="button" class="btn btn-default"> Expired </button>
            <% elsif event.overbooked? == true %>
              <button type="button" class="btn btn-danger"> Overbooked </button>
            <% elsif event.full? == true %>
              <button type="button" class="btn btn-warning"> Full </button>
            <% elsif event.already_applied?(current_user) %>
              <button type="button" class="btn btn-info"> Already Applied </button>
            <% else %>
              <%= form_for(@job) do |f| %>
              <%= f.hidden_field :event_id, :value => event.id %>
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <div class='action'>
              <%= f.submit :class => "btn btn-success btn-mini" %>
              </div>
              <% end %>
            <% end %>
          <% end %>
          <% if event.expired? == true and event.overbooked? == false and event.full? == false and event.already_applied?(current_user) == false and current_user.user_level != 'Managment' %>
    <td> <%= event.event %></td>
    <td> date: <%= event.event_time_start %></td>
    <td>  <%= event.event_type %> </td>
    <td>Slots: <%= event.slots %> / <%= event.jobs_count %></td>
    <td>
               <%= form_for(@job) do |f| %>
                  <%= f.hidden_field :event_id, :value => event.id %>
                  <%= f.hidden_field :user_id, :value => current_user.id %>
                  <div class='action'>
                  <%= f.submit :class => "btn btn-success btn-mini" %>
                  </div>
               <% end %>
          <% end %>
    </td>
</tr>
<% end %>
</table>
<br>
<%= link_to 'Back', jobs_path, class: 'btn btn-default' %>

app/views/jobs/show.html.erb
<div>
<strong>#id - </strong><%= @job.id %><br>
<strong>Event Name - </strong><%= @job.event.event %><br>
<strong>Event Type - </strong><%= @job.event.event_type %><br>
<strong>Event Date/Time - </strong><%= @job.event.event_time_start %> to
  <%= @job.event.event_time_finish %> - <strong><%= ((@job.event.event_time_finish.to_i - @job.event.event_time_start.to_i) / 3600) %> Hours </strong><br>
<strong>Event Location - </strong><%= @job.event.location %><br>
<br>

INSERT MAP / PHOTO OF LOCATION HERE.

</div>

<%= link_to 'Back', jobs_path, class: 'btn btn-default'  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>WDIProject1</title>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

</head>
<body>
<div class='container-fluid'>
	<div class='row header'>
	 <div class='logo col-md-3'>
		<%= link_to 'Home / logo', root_path %>
	 </div>
		<div class='login col-md-3 col-md-push-6'>
		 <% if user_signed_in? %>
			Logged in as <strong><%= current_user.email %></strong> - #<%= current_user.id %><br>
			<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		 <% else %>
			<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
			<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		 <% end %>
		</div>
	</div>
 <div class="row">
	 <div class="content col-md-8 col-md-offset-2">

	 <%= yield %>

	 </div>
 </div>
 <div class='row'>
 <div class='footer col-md-12'>
 	<div class='footer_content'>
	Footer
	</div>
 </div>
</div>
</div>
</body>
</html>

app/views/users/sign_out.html.erb
You are now Signed out.
<%= link_to 'Back', root_path, class: 'btn btn-default' %>